name: HelpMeSpeak
description: "AI Chat App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Connectivity Checker
  connectivity_plus: ^6.1.1

  # Cached Network Images
  cached_network_image: ^3.3.1

  # Navigation
  go_router: ^16.2.0

  # Assets Generator
  flutter_gen: ^5.5.0+1

  # OTP Verification
  flutter_verification_code: ^1.1.7

  # Firebase Core
  #firebase_core: ^3.5.0

  # Firebase Authentication
  #firebase_auth: ^5.3.0

  # Google Sign-In
  google_sign_in: ^7.1.1

  # Apple Sign-In
  sign_in_with_apple: ^7.0.1
  pin_code_fields: ^8.0.1

  # Voice conversion
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  device_preview: ^1.3.1
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_asset_generator: ^1.2.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
